"""Explicit registration surface for approved Phase 1D-1B ORM models."""

from typing import Final

from creativedeploy_api.db.base import Base
from creativedeploy_api.db.models.ai_foundation import (
    AIAuditEvent,
    AICommandIdempotencyRecord,
    AICostLedger,
    AIInvocationEvent,
    AIUsageLedger,
    BudgetReservation,
    CapabilityDefinition,
    CredentialProjectGrant,
    CredentialRecord,
    InvocationAttempt,
    InvocationRequest,
    ModelCapability,
    ModelDefinition,
    ProjectBudgetCounter,
    ProjectBudgetPolicy,
    ProjectModelPolicy,
    ProjectModelPolicyCapability,
    ProjectModelPolicyCredential,
    ProjectModelPolicyModel,
    ProjectModelPolicyProvider,
    ProviderCapability,
    ProviderDefinition,
    UserBudgetCounter,
    UserBudgetPolicy,
    UserProviderPreference,
)
from creativedeploy_api.db.models.command_idempotency_record import (
    CommandIdempotencyRecord,
)
from creativedeploy_api.db.models.identity import (
    AuthSession,
    ExternalIdentity,
    OidcLoginFlow,
    ProjectMembership,
    UserAccount,
)
from creativedeploy_api.db.models.image_asset import ImageAsset
from creativedeploy_api.db.models.image_set_readiness_review import (
    ImageSetReadinessReview,
)
from creativedeploy_api.db.models.paint_project import PaintProject
from creativedeploy_api.db.models.region_set import (
    Region,
    RegionSet,
    RegionSetReview,
    RegionVertex,
)
from creativedeploy_api.db.models.state_transition_event import StateTransitionEvent

REGISTERED_MODELS: Final[tuple[type[Base], ...]] = (
    PaintProject,
    StateTransitionEvent,
    CommandIdempotencyRecord,
    ImageAsset,
    ImageSetReadinessReview,
    UserAccount,
    ExternalIdentity,
    ProjectMembership,
    OidcLoginFlow,
    AuthSession,
    RegionSet,
    Region,
    RegionVertex,
    RegionSetReview,
    ProviderDefinition,
    CapabilityDefinition,
    ModelDefinition,
    ProviderCapability,
    ModelCapability,
    CredentialRecord,
    CredentialProjectGrant,
    UserProviderPreference,
    ProjectModelPolicy,
    ProjectModelPolicyProvider,
    ProjectModelPolicyModel,
    ProjectModelPolicyCapability,
    ProjectModelPolicyCredential,
    UserBudgetPolicy,
    ProjectBudgetPolicy,
    UserBudgetCounter,
    ProjectBudgetCounter,
    InvocationRequest,
    InvocationAttempt,
    BudgetReservation,
    AIInvocationEvent,
    AIUsageLedger,
    AICostLedger,
    AIAuditEvent,
    AICommandIdempotencyRecord,
)

__all__ = [
    "REGISTERED_MODELS",
    "AIAuditEvent",
    "AICommandIdempotencyRecord",
    "AICostLedger",
    "AIInvocationEvent",
    "AIUsageLedger",
    "AuthSession",
    "BudgetReservation",
    "CapabilityDefinition",
    "CommandIdempotencyRecord",
    "CredentialProjectGrant",
    "CredentialRecord",
    "ExternalIdentity",
    "ImageAsset",
    "ImageSetReadinessReview",
    "InvocationAttempt",
    "InvocationRequest",
    "ModelCapability",
    "ModelDefinition",
    "OidcLoginFlow",
    "PaintProject",
    "ProjectBudgetCounter",
    "ProjectBudgetPolicy",
    "ProjectMembership",
    "ProjectModelPolicy",
    "ProjectModelPolicyCapability",
    "ProjectModelPolicyCredential",
    "ProjectModelPolicyModel",
    "ProjectModelPolicyProvider",
    "ProviderCapability",
    "ProviderDefinition",
    "Region",
    "RegionSet",
    "RegionSetReview",
    "RegionVertex",
    "StateTransitionEvent",
    "UserAccount",
    "UserBudgetCounter",
    "UserBudgetPolicy",
    "UserProviderPreference",
]
